wtf:
  colors:
    border:
      focusable: #9f8578
      focused: #cab0a1
      normal: #585c69
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    spotify:
      enabled: true
      colors:
        label: "green"
        text: "white"
      position:
        top: 0
        left: 2
        height: 1
        width: 1
      refreshInterval: 0
    digitalclock:
      color: "#cab0a1"
      enabled: true
      font: bigfont
      hourFormat: 12
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 1s
      title: "big clock"
      type: "digitalclock"
    feedreader:
      enabled: true
      feeds:
      - https://asec.ahnlab.com/ko/feed
      feedLimit: 10
      position:
        top: 1
        left: 1
        width: 2
        height: 1
      refreshInterval: 14400
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: false
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 30
      type: cmdrunner

    todo:
      checkedIcon: "X"
      colors:
        checked: gray
        highlight:
          fore: "#333232"
          back: "#cab0a1"
      enabled: true
      filename: "todo.yml"
      position:
        top: 2
        left: 1
        height: 1
        width: 1
      refreshInterval: 1h
    power:
      enabled: true
      position:
        top: 2
        left: 2
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    textfile:
      enabled: true
      filePath: "~/my_github/my_dots/quote.txt"
      format: true
      position:
        top: 0
        left: 0
        height: 4
        width: 1
      refreshInterval: 30
      wrapText: true
